### PR TITLE
Updated signs.json

### PR DESCRIPTION
**Pull request by TheEpicness9000**
I finished updating the .json file responsible for sign naming and tooltips. This makes sign names more consistent and adds tooltips/notes to some signs that didn't have them before. There are no more duplicate IDs.

### CODE REVIEW

**Review by CSX8600 — CHANGES_REQUESTED** [review]
Some of this json is invalid.  I recommend running it through a json validator tool online to identify and correct these problems.

**Comment by TheEpicness9000** [comment]
Signs.json has been validated and is ready to be merged.

**Comment by CSX8600** [comment]
I ran it through jsonlint.com and it still found a problem
image
With a validator too like jsonlint.com, you'll have to keep running your modified json through it after every change until it shows that it is 100% valid.  In other words, it only finds one error at a time when there really could be potentially hundreds.

**Comment by TheEpicness9000** [comment]
The final errors have been resolved. Jsonlint reports no errors.

**Comment by TheEpicness9000** [comment]
All it found were a few commas.

**Review by CSX8600 — APPROVED** [review]

**Pull request merged**
